Description: "Sample of Î»-function's template."
Globals:
  Function:
    Timeout: 5
Resources:
  mainFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: main.zip
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Events:
        Health:
          Type: Api
          Properties:
            Path: /
            Method: GET
      Environment:
        Variables: